//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Avenidas.
        /// </summary>
        internal static string AdicionarSubgrupos {
            get {
                return ResourceManager.GetString("AdicionarSubgrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique sobre uma Avenida.
        /// </summary>
        internal static string InfoCliqueSobreSubgrupo {
            get {
                return ResourceManager.GetString("InfoCliqueSobreSubgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique sobre as Avenidas abaixo para exibição de detalhes.
        /// </summary>
        internal static string InfoDetalheSubgrupos {
            get {
                return ResourceManager.GetString("InfoDetalheSubgrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTA QUADRA NÃO POSSUI NENHUMA AVENIDA.
        /// </summary>
        internal static string InfoNenhumSubgrupo {
            get {
                return ResourceManager.GetString("InfoNenhumSubgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações para Criação de Avenidas.
        /// </summary>
        internal static string InformacoesParaCriacaoDeSubgrupos {
            get {
                return ResourceManager.GetString("InformacoesParaCriacaoDeSubgrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Avenidas.
        /// </summary>
        internal static string LabelAdicionarSubgrupos {
            get {
                return ResourceManager.GetString("LabelAdicionarSubgrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadra.
        /// </summary>
        internal static string LabelGrupo {
            get {
                return ResourceManager.GetString("LabelGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificação da Primeira Avenida.
        /// </summary>
        internal static string LabelIdentificacaoPrimeiroSubgrupo {
            get {
                return ResourceManager.GetString("LabelIdentificacaoPrimeiroSubgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotes da Avenida.
        /// </summary>
        internal static string LabelLotesDoSubgrupo {
            get {
                return ResourceManager.GetString("LabelLotesDoSubgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de Avenidas.
        /// </summary>
        internal static string LabelQuantidadeSubgrupos {
            get {
                return ResourceManager.GetString("LabelQuantidadeSubgrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenida.
        /// </summary>
        internal static string LabelSubgrupo {
            get {
                return ResourceManager.GetString("LabelSubgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenidas da Quadra.
        /// </summary>
        internal static string LabelSubgruposDoGrupo {
            get {
                return ResourceManager.GetString("LabelSubgruposDoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listagem de Quadras.
        /// </summary>
        internal static string ListagemGrupos {
            get {
                return ResourceManager.GetString("ListagemGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Quadra.
        /// </summary>
        internal static string NovoGrupo {
            get {
                return ResourceManager.GetString("NovoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadra &quot;{0}&quot; Avenida &quot;{1}&quot;.
        /// </summary>
        internal static string StringFormatGrupoSubgrupo {
            get {
                return ResourceManager.GetString("StringFormatGrupoSubgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadra &quot;{0}&quot; Avenida &quot;{1}&quot; Lote &quot;{2}&quot;.
        /// </summary>
        internal static string StringFormatGrupoSubgrupoLote {
            get {
                return ResourceManager.GetString("StringFormatGrupoSubgrupoLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotes da Quadra &quot;{0}&quot; Avenida &quot;{1}&quot;.
        /// </summary>
        internal static string StringFormatLotesDoSubgrupoGrupo {
            get {
                return ResourceManager.GetString("StringFormatLotesDoSubgrupoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avenidas da Quadra &quot;{0}&quot;.
        /// </summary>
        internal static string StringFormatSubgruposDoGrupo {
            get {
                return ResourceManager.GetString("StringFormatSubgruposDoGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar para Quadras.
        /// </summary>
        internal static string VoltarParaGrupos {
            get {
                return ResourceManager.GetString("VoltarParaGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar para Lotes da Avenida.
        /// </summary>
        internal static string VoltarParaLotesDoSubgrupo {
            get {
                return ResourceManager.GetString("VoltarParaLotesDoSubgrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar para Avenidas da Quadra.
        /// </summary>
        internal static string VoltarParaSubgruposDoGrupo {
            get {
                return ResourceManager.GetString("VoltarParaSubgruposDoGrupo", resourceCulture);
            }
        }
    }
}
